export type Keys =
  | 'SEARCH'
  | 'LOGOUT'
  | 'MOVIES'
  | 'SCIENCE_FICTION'
  | 'FANTASTIC'
  | 'DRAMA'
  | 'COMEDY'
  | 'DOCUMENTARY'
  | 'GET_MORE'
  | 'LOGIN'
  | 'OK'
  | 'FAILED'
  | 'USERNAME_OR_PASSWORD_IS_WRONG'
